PAKKY_FLAGS="-march=native -O2 -pipe"
CFLAGS="${PAKKY_FLAGS}"
CXXFLAGS="${PAKKY_FLAGS}"
MODULES="${FEATURES} getbinpkg"
LDFLAGS="${PAKKY_FLAGS} -Wl,-O1 -Wl,--as-needed"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
PAKKING="-j4 -l5"